import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import * as d3 from 'd3';
import data from './../data.json';
import useWindowSize from '../hooks/windowSize';
import TooltipComponent from '../components/Tooltip';

export default function Home() {
  const { clientWidth, clientHeight } = useWindowSize();
  const containerRef = useRef(null);
  const [tooltipVars, setTooltipVars] = useState(null);

  useEffect(() => {
    if (containerRef.current && clientWidth && clientHeight) {
      const margin = { top: 5, right: 25, bottom: 30, left: 40 };
      const width = clientWidth - margin.left - margin.right;
      const height = clientHeight - margin.top - margin.bottom;

      let arr = [];
      while (arr.length < 5) {
        let num = Math.floor(Math.random() * data.length) + 1;
        if (!arr.includes(num)) {
          arr.push(num);
        }
      }

      const svg = d3.select(containerRef.current)
        .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

      const xData = d3.map(data, function (d) { return d.group; });
      const yData = d3.map(data, function (d) { return d.variable; });

      const x = d3.scaleBand()
        .range([0, width])
        .domain(xData)
        .padding(0.05)
      svg.append("g")
        .style("font-size", 12)
        .attr("transform", "translate(0," + height + ")")
        .call(
          d3.axisBottom(x)
            .tickSize(0)
        )

      const y = d3.scaleBand()
        .range([height, 0])
        .domain(yData)
        .padding(0.05)
      svg.append("g")
        .style("font-size", 12)
        .call(
          d3.axisLeft(y)
            .tickSize(0)
        )

      const mousemove = function (event, d) {
        event.preventDefault();
        const { clientX, clientY } = event;
        const value = data.findIndex(el => el.value === d.value)
        if (arr.includes(value + 1)) {
          console.log("Explodiu...");
          d3.select(this)
            .style("fill", "purple")
          setTooltipVars(state => ({ ...d, clientX, clientY, opacity: 1, message: "Boooom!!!" }));
        } else {
          setTooltipVars(state => ({ ...d, clientX, clientY, opacity: 1, message: "Ufa!!!" }));
        }
      }
      const mouseleave = function (event) {
        event.preventDefault();
        setTooltipVars(state => ({ ...state, opacity: 0 }));
        d3.select(this)
          .style("opacity", 1)
      }

      svg.selectAll()
        .data(data, function (d) { return d.value; })
        .join("rect")
        .attr("x", function (d) { return x(d.group) })
        .attr("y", function (d) { return y(d.variable) })
        .attr("width", x.bandwidth())
        .attr("height", y.bandwidth())
        .style("fill", function (ev, d) {
          // if (arr.includes(d + 1)) {
          //   return "purple";
          // }
          return "olive";
        })
        .on("click", mousemove)
        .on("mouseleave", mouseleave)

      svg.selectAll()
        .data(data, function (d) { return d.value; })
        .join("text")
        .attr("x", function (d) { return x(d.group) + x.bandwidth() / 4 })
        .attr("y", function (d) { return y(d.variable) + 20 })
        .text(function (d) { return d.value })
        .on("click", mousemove)
    }

  }, [clientWidth, clientHeight]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div ref={containerRef}>
        {tooltipVars
          && <TooltipComponent
            d={tooltipVars}
            width={clientWidth}
            height={clientHeight}
          />}
      </div>

    </div>
  )
}
