import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import * as d3 from 'd3';
import data from './../data.json';
import useWindowSize from '../hooks/windowSize';
import TooltipComponent from '../components/Tooltip';

export default function Home() {
  const { clientWidth, clientHeight } = useWindowSize();
  const containerRef = useRef(null);
  const svgGroupRef = useRef();
  const [tooltipVars, setTooltipVars] = useState(null);
  const margin = { top: 5, right: 25, bottom: 30, left: 25 };
  const width = clientWidth - margin.left - margin.right;
  const height = clientHeight - margin.top - margin.bottom;
  const svgWidth = width + margin.left + margin.right;
  const svgHeight = height + margin.top + margin.bottom;

  useEffect(() => {
    if (containerRef.current && clientWidth && clientHeight) {
      let arr = [];
      while (arr.length < 5) {
        let num = Math.floor(Math.random() * data.length) + 1;
        if (!arr.includes(num)) {
          arr.push(num);
        }
      }

      const svgGroup = d3.select(svgGroupRef.current)
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

      const xData = d3.map(data, function (d) { return d.group; });
      const yData = d3.map(data, function (d) { return d.variable; });

      const x = d3.scaleBand()
        .range([0, width])
        .domain(xData)
        .padding(0.05)
      d3.select(".x-axis")
        .style("font-size", 12)
        .attr("transform", "translate(0," + height + ")")
        .call(
          d3.axisBottom(x)
            .tickSize(0)
        )
        .select(".domain").remove()
        .select(".tick").remove()

      const y = d3.scaleBand()
        .range([height, 0])
        .domain(yData)
        .padding(0.05)
      d3.select(".y-axis")
        .style("font-size", 12)
        .call(
          d3.axisLeft(y)
            .tickSize(0)
        )
        .select(".domain").remove()
        .select(".tick").remove()

      const mousemove = function (event, d) {
        event.preventDefault();
        const { clientX, clientY } = event;
        const value = data.findIndex(el => el.value === d.value);
        if (arr.includes(value + 1)) {
          d3.select(this)
            .attr("xlink:href", "https://previews.123rf.com/images/fil101/fil1011109/fil101110900010/10589503-furbul-cg-character-with-a-question-mark-hovering-above-his-head-.jpg")
            // setTooltipVars(state => ({ ...d, clientX, clientY, opacity: 1, message: "Boooom!!!" }));
        } else {
          d3.select(this).attr("opacity", 0.1)
          // setTooltipVars(state => ({ ...d, clientX, clientY, opacity: 1, message: "Ufa!!!" }));
        }
      }
      const mouseleave = function (event) {
        event.preventDefault();
        // setTooltipVars(state => ({ ...state, opacity: 0 }));
        // d3.select(this)
        //   .style("opacity", 1)
      }

      const groups = svgGroup.selectAll()
        .data(data)
        .join("g")
        .attr("transform", d => `translate(${x(d.group)},${y(d.variable)})`)

      groups.each(function (d) {
        d3.select(this)
          .append("defs").selection()
          .append("clipPath").attr("id", d.value).selection()
          .append("rect")
          .attr("width", x.bandwidth())
          .attr("height", y.bandwidth())
          .attr("fill", "steelblue")

        d3.select(this)
          .append("image")
          .attr("xlink:href", "https://previews.123rf.com/images/blankstock/blankstock1605/blankstock160503065/56324157-question-mark-sign-icon-help-symbol-faq-sign-orange-circle-button-with-icon-vector.jpg") 
          .attr("width", x.bandwidth())
          .attr("height", y.bandwidth())
          .attr("clip-path", `url(#${d.value})`)
          .on("click", mousemove)
          .on("mouseleave", mouseleave);
      })
    }

  }, [clientWidth, clientHeight]);

  const hasSvgDimensions = () => {
    return (!isNaN(svgWidth) && !isNaN(svgHeight));
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div ref={containerRef}>
        {hasSvgDimensions() && <svg id="svg-container" width={svgWidth} height={svgHeight}>
          <g ref={svgGroupRef} className="group-1">
            <g className="x-axis"></g>
            <g className="y-axis"></g>
          </g>
        </svg>}
        {/* {tooltipVars
          && <TooltipComponent
            d={tooltipVars}
            width={clientWidth}
            height={clientHeight}
          />} */}
      </div>

    </div>
  )
}
